### ISSUE TITLE
remember location for file import

### ISSUE THREAD

**Issue by nitrada** [thetylerwolf/sketch-data-studio#6]
I usually have several CSV files to import with the plugin in the same folder on my computer. however, after importing a CSV, then importing another one, the recent location won't be remembered. would be great if it would! :-)

**Comment by thetylerwolf** [comment]
I'll look into how to implement this. Learning how to work with the cocoa api as I go along :)

**Comment by thetylerwolf** [comment]
Good thinking. Updated this.

**Comment by nitrada** [comment]
👏
