### ISSUE TITLE
Broken in 3.8

### ISSUE THREAD

**Issue by sogen** [thetylerwolf/sketch-data-studio#9]
When running "Line chart" or "Bar chart", it doesn't generate them, just creates an empty folder,
Opened Sketch 3.7.1 and plugin works.

OSX: Yosemite 10.10.5

**Comment by thetylerwolf** [comment]
Fixed. Thanks!

**Comment by mlaw-skyport** [comment]
Exact same broken behavior in macOS: Sierra 10.12.4 (16E195) + Sketch v. 43.2. Is this plugin still being maintained?

**Comment by thetylerwolf** [comment]
The plugin is still being maintained, but I'm not able to reproduce this issue. Are you able to send a console trace for when it fails?

**Comment by mlaw-skyport** [comment]
Happy to do it if you explain how to do that.

**Comment by thetylerwolf** [comment]
Sure thing:
1 - Open your applications folder, then open the "Utilities" folder, now open "Console"
2 - Type "Sketch" in the search bar on the top right of the window
3 - Click "Clear" at the top of the window
4 - Run the plugin in your Sketch Window. Something should pop up in the list in the Console window. It should have a small triangle to the left of it. Click to expand the message and take a screenshot.
5 - Send it my way! (post it here)

**Comment by mlaw-skyport** [comment]
Thank you for the clear instructions!

No expandable triangles, but I'm highlighting details behind the error log message here:

![sketch-console](https://cloud.githubusercontent.com/assets/7718699/25447399/e613d63a-2a69-11e7-9919-de23302b350e.png)

Thx!

**Comment by thetylerwolf** [comment]
Ah very helpful! The problem is that you don't have the latest version. You're one commit behind. Just download the plugin from the github page and reinstall it. You should be good to go!

**Comment by mlaw-skyport** [comment]
Really dumb question: how do I download latest premium? github page (https://github.com/thetylerwolf/sketch-data-studio) appears to be free version, and premium page (http://thetylerwolf.github.io/sketch-data-studio/) offers only "try it free" and "buy" options. I've already purchased it. Thanks for any advice.

**Comment by thetylerwolf** [comment]
Ah, I had no idea you've already bought it! You can send any issues in the future to the support email. I'll send you the latest version right now.

**Comment by mlaw-skyport** [comment]
Thanks, Tyler. Got it, installed it, and back in business. :)
